### ISSUE TITLE
Conversion failed: Error: spawn C:\\Windows\system32\cmd.exe ENOENT

### ISSUE THREAD

**Issue by jhconning** [danielfrg/atom-nbviewer#2]
That's the error I get in the Preview pane.   Any idea what might be the cause?

I'm running on a Windows 10 x64 machine.  I have pandoc and nbconvert installed and working fine in other uses.  The Jupyter Convert Bin address I entered in settings is:
"C:\Users\Jonathan\Anaconda3\pkgs\nbconvert-4.1.0-py34_0\Scripts\jupyter-nbconvert.exe"

**Comment by danielfrg** [comment]
I dont really know windows so i have no idea. I'll try to get access to a windows box and see if i can reproduce.

**Comment by AStupidBear** [comment]
@danielfrg I can reproduce this. Hoping for fix!

**Comment by AStupidBear** [comment]
I think that's due to ``/tmp``
