### ISSUE TITLE
Conversion fails

### ISSUE THREAD

**Issue by gvoronov** [danielfrg/atom-nbviewer#3]
When I try to use this package, I get the following error:
Conversion failed: Error: spawn C:\WINDOWS\system32\cmd.exe ENOENT

Note  jupyter-nbconvert executable installed and functions properly.

**Comment by danielfrg** [comment]
I have never tried this on windows and it probably doesn't work but it should be easy to fix.

Maybe you or someone who has access to a windows machine could make a small PR to fix it.
